[FEAT] 회원의 데일리 루틴 목록 조회
Team-Sopetit/Sopetit-server pull request #278
Opened 2024-06-18 08:35 UTC by Chan531

## ✨ Related Issue
- close #273 
  <br/>

## 📝 기능 구현 명세
![image](https://github.com/Team-Sopetit/Sopetit-server/assets/81404890/e77bcf14-730a-41f6-80b2-848192b20bf8)
- 회원의 데일리 루틴 목록 조회 api

![image](https://github.com/Team-Sopetit/Sopetit-server/assets/81404890/f54c494e-446b-482a-8764-e02c1b9355cd)
- 회원의 데일리 루틴 목록 조회 api 테스트

## 🐥 추가적인 언급 사항
- 최대한 controller 단에서만 v2를 작성하려고 했는데 그게 여의치 않아서 service 단에서 v2 관련 메소드와 dto가 꽤 추가되었습니다.
- 맞는 방식인지 궁금합니다.
- 현재 루틴은 가나다순으로 정렬이 된 상태지만, 테마는 무지개순으로 정렬되지 않은 상태입니다.
- 테마를 어떻게 해야 무지개순으로 정렬해야할지 고민 중입니다... (꽤나 까다로움)
- 현재까지 테마를 무지개순으로 정렬하는 방안은 다음과 같습니다
1. E로 시작하는 색이 앞에 온다.
2. 16진수의 두번째 문자를 15로 나눈 나머지가 작을 수록 앞에 온다. 만약 같을 경우 그 수가 작은 것이 앞에 온다. 
(ex. E19098과 EF596F는 나머지가 같기 때문에 전자가 앞에 온다.
       EDBF4F과 EB9D07는 후자가 앞에 온다.)
3. E로 시작하지 않는다면 사전순으로 작을 수록 앞에 온다.
(ex. 52A1DA는 6392D8보다 앞에 온다.)
- 이렇게까지 해야하나 싶어서 일단 테마 무지개순 정렬은 보류했습니다.

2024-06-18 12:07 UTC, thguss requested changes
수고하셨습니다.
서비스 계층에서 버저닝만 제거하면 좋을 것 같습니다.
추가로, 작성한 리뷰는 작성자가 직접 resolve하는 것이 어떨까요!? 작성한 리뷰가 반영되었는지 다시 확인해야하는데 이미 resolve 되어 있으면 진행이 불편해지는 감이 있어 요청 드립니다 :)

2024-06-18 12:07 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/MemberDailyRoutineControllerV2.java
> +                .of(memberRoutineReadService.getDailyRoutinesV2(MemberDailyRoutineListGetServiceRequest.of(memberId)));
서비스 계층에는 버저닝(v2)이 존재하지 않도록 해주세요!

2024-06-18 12:07 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineListGetResponse.java
> +    public static MemberDailyRoutineListGetResponse of(MemberDailyRoutineListGetServiceResponseV2 tempB) {
좀 더 의미 있는 변수명으로 변경 요청드립니다!

2024-06-18 12:07 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineListGetResponse.java
> +    public static MemberDailyRoutineListGetResponse of(MemberDailyRoutineListGetServiceResponseV2 tempB) {
서비스 계층에서 사용하는 DTO이므로 이름에 버저닝(v2)이 포함되지 않도록 해주세요.

2024-06-18 12:07 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberRoutineResponse.java
> +		Long themeId,
nullable 여부에 따라서 원시형, 래퍼형 나뉠 것 같은데 확인 한 번 부탁드립니다~

2024-06-18 12:07 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineReadService.java
> +	public MemberDailyRoutineListGetServiceResponseV2 getDailyRoutinesV2(
서비스 계층에서는 비즈니스 로직을 담당하기 때문에, 버저닝이 포함되면 안됩니다!
- v1 컨트롤러에서 사용하던 메서드를 재활용하거나,
- 좀 더 의미있는 메서드명으로 변경하는 것이 필요해보입니다.

2024-06-18 12:07 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineGetServiceResponseV2.java
> +public record MemberDailyRoutineGetServiceResponseV2(
v1 컨트롤러에서 사용하던 DTO를 재활용하거나, 의미있는 이름으로 버저닝은 제외하고 변경 부탁드립니다.

2024-06-19 01:24 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/MemberDailyRoutineControllerV2.java
> +                .of(memberRoutineReadService.getDailyRoutinesV2(MemberDailyRoutineListGetServiceRequest.of(memberId)));
넵 테마별로 데일리 루틴을 가져온다는 뜻에서 getDailyRoutinesByTheme으로 변경했습니다.

2024-06-19 01:29 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineListGetResponse.java
> +    public static MemberDailyRoutineListGetResponse of(MemberDailyRoutineListGetServiceResponseV2 tempB) {
개발하고 수정하다 미처 발견 못했네요ㅠㅠ 수정했습니다.

2024-06-19 01:30 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineListGetResponse.java
> +    public static MemberDailyRoutineListGetResponse of(MemberDailyRoutineListGetServiceResponseV2 tempB) {
dto명에 v2 대신 테마로 묶어서 전송한다는 의미로 ByTheme 추가하였습니다.

2024-06-19 01:33 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineReadService.java
> +	public MemberDailyRoutineListGetServiceResponseV2 getDailyRoutinesV2(
- MemberDailyRoutineListGetServiceResponseV2 -> MemberDailyRoutineByThemeListGetServiceResponse
- getDailyRoutinesV2 -> getDailyRoutinesByTheme

으로 각각 수정하였습니다!

2024-06-19 01:34 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineGetServiceResponseV2.java
> +public record MemberDailyRoutineGetServiceResponseV2(
- MemberDailyRoutineGetServiceResponseV2 -> MemberDailyRoutineByThemeGetServiceResponse

으로 수정하였습니다!

2024-06-19 01:56 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberRoutineResponse.java
> +		Long themeId,
MemberRoutineResponse와 MemberChallengeResponse의 기존 코드가 따로 nullable을 고려하지 않은 거 같아서 코드 맞춰 작성했는데 nonnull과 Long -> long 고려해야할까요?

답변 받고 수정하도록 하겠습니다.

2024-06-19 02:17 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/MemberDailyRoutineControllerV2.java
> +    public ResponseEntity<SuccessResponse<MemberDailyRoutineListGetResponse>> getMemberDailyRoutines(
(기존부터 적용되어 있던 거긴 하지만..!) 코드를 보다보니 메서드 이름이 하나둘씩 길어지는 것 같아서 `MemberDailyRoutine` 같은 **prefix는 제거**하고 가져가는 방향은 어떤가요?? 추가로 CRUD 워딩은 레포지토리 계층에서만 사용하고, Controller, Service 계층에서는 **유저 액션에 가까운 워딩**을 쓰는 방식도 좋을 것 같습니다! (ex. `searchAllByTheme`)

클래스 이름부터 `MemberDailyRoutineController`이니까 행위만 가져가도 좋을 것 같다는 의견입니다!

2024-06-19 02:17 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberRoutineResponse.java
> +		Long themeId,
음 코드를 맞추는 방향도 좋지만, DTO 내에서 사용하는 독립적인 필드이기 때문에 DTO 내에서 nullable 여부에 집중하는 것이 좋을 것 같습니다! `themeId`라는 필드가 null이 들어올 수 있다면 래퍼 타입으로, 그렇지 않다면 원시 타입으로 가져가는 것이 이후 NPE에 대응하기 유리할 것 같습니다!

2024-06-19 02:22 UTC, thguss reviewed
수고하셨습니다 👍 
의논이 필요해보이는 사항이 있어 comment로 남깁니다!
리뷰 또는 소통 채널에서 의견 공유하면 좋을 것 같습니다~

2024-06-19 02:22 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineReadService.java
위 리뷰에 작성했지만, 해당 클래스에서도

- 메서드 이름에서 Entity prefix 제거
- CRUD 외 유저 액션 친화적인 워딩 사용

이 고려되면 좋을 것 같습니다!

2024-06-19 04:25 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberRoutineResponse.java
> +		Long themeId,
카톡 논의 후 db에서 null값인 컬럼이 없기 때문에 String은 Nonnull 처리해주고 Long은 long으로 바꿔주는게 맞다 생각해서 이런 방향으로 수정완료했습니다.

2024-06-19 05:00 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/MemberDailyRoutineControllerV2.java
> +    public ResponseEntity<SuccessResponse<MemberDailyRoutineListGetResponse>> getMemberDailyRoutines(
동의합니다! 고민하다 아래와 같이 변경하였습니다.

- MemberDailyRoutineByThemeGetServiceResponse -> ViewWithThemeServiceResponse
- MemberDailyRoutineByThemeListGetServiceResponse -> ViewAllWithThemeServiceResponse
-> 데일리 루틴을 조회하는 행동이기 때문에 View로 명칭하였습니다.
-> 테마별로 구분하는 것이 아닌 테마와 함께 루틴을 반환하기 때문에 By를 With으로 변경하였습니다.

- MemberRoutineServiceResponse -> InfoSerivceResponse
-> 루틴 정보를 포함하기 때문에 다음과 같이 변경하였습니다.

2024-06-19 05:11 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/ViewAllWithThemeServiceResponse.java
> +public record ViewAllWithThemeServiceResponse(
엇 DTO 이름 쪽은 기존대로 Entity 명을 포함하는 게 좋지 않을까요!?
이전 리뷰에서 언급한 이름은 메서드 대상이긴 했습니다..!

2024-06-19 05:11 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/MemberDailyRoutineControllerV2.java
> +    public ResponseEntity<SuccessResponse<MemberDailyRoutineListGetResponse>> getMemberDailyRoutines(
엇 제가 말한 건 DTO가 아닌 메서드 대상이었습니다 ㅠㅠ!!

2024-06-19 05:12 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/MemberDailyRoutineControllerV2.java
> +    public ResponseEntity<SuccessResponse<MemberDailyRoutineListGetResponse>> getMemberDailyRoutines(
방금 내 세상이 무너졋서

2024-06-19 09:04 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineReadService.java
> +	public MemberDailyRoutineWithThemeListGetServiceResponse acquire(
Controller와 마찬가지로, 메서드 이름에서 복수형의 의미가 추가로 전달되면 좋을 것 같습니다.

2024-06-19 09:04 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineWithThemeGetServiceResponse.java
해당 DTO 또한 `WithTheme` 와 같은 과도한 정보를 가지고 있는 것 같습니다..!

2024-06-19 09:04 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineWithThemeListGetServiceResponse.java
> +    public static MemberDailyRoutineWithThemeListGetServiceResponse of(List<MemberDailyRoutineWithThemeGetServiceResponse> routines) {
한 줄이 좀 길어지는데, 한 줄 띄어쓰기로 정리하면 좋을 것 같습니다!

```
public static MemberDailyRoutineWithThemeListGetServiceResponse of(
  List<MemberDailyRoutineWithThemeGetServiceResponse> routines
) {
...
```

2024-06-19 09:04 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineWithThemeListGetServiceResponse.java
> +    public static MemberDailyRoutineWithThemeListGetServiceResponse of(List<MemberDailyRoutineWithThemeGetServiceResponse> routines) {
혹시 DTO 이름 변경(과도한 정보 생략) 후 줄이 짧아지게 되면 그냥 넘어가도 될 것 같네요!

2024-06-19 09:11 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineWithThemeListGetResponse.java
만약 다른 DTO와의 이름 중복을 피하기 위한 것이라면,
Controller에서 사용하는 DTO 이름에는 `V2`를 추가하여 구분해도 좋은 방법이 될 것 같습니다!
또한, Service에서 사용하는 DTO는 V1 때 사용했던 DTO를 재활용해볼 수 없을까요!? (ex. 루틴 DTO에 테마 필드를 추가하고, Controller DTO로 변환하는 단계에서 테마 필드를 묶게 한다던지..!)

2024-06-19 11:58 UTC, Chan531 commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineWithThemeListGetResponse.java
중복을 피하고자 했던거라 controller 단에서는 v2를 추가하여 구별하였습니다.
또한, service 단에서 같은 dto를 쓰게끔 수정하였습니다.
이 과정에서 dto명이 바뀌었는데 확인해주시면 감사하겠습니다.

v1의 데일리 루틴 조회 api에서는 MemberDailyRoutineGetServiceResponse를 controller 단에 넘겨주고
v2의 데일리 루틴 조회 api에서는 MemberDailyRoutineListGetServiceResponse를 controller 단에 넘겨준다고 이해해주시면 될 거 같습니다.

MemberDailyRoutineListGetServiceResponse 말고 List<MemberDailyRoutineGetServiceResponse>를 controller 단에 넘겨주는 방법도 생각해봤는데 service -> controller로 데이터를 넘겨줄 때 더이상 가공이 들어가지 않는 동일한 구조의 데이터를 넘겨주는게 맞다 생각하여 굳이 dto를 하나 더 추가하는 작업을 했는데 코멘트 남겨주시면 감사하겠습니다.

2024-06-19 12:30 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v1/dto/response/MemberDailyRoutineListGetResponse.java
Controller 계층 쪽이니까 Get 대신 메서드명에서 사용한 Acquire로 대체되면 더 자연스러울 것 같습니다!

2024-06-19 12:36 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineGetServiceResponse.java
해당 DTO 내에서 루틴 목록을 포함하고 있기 때문에 복수형의 의미가 전달되는 워딩이 추가되면 좋을 것 같긴 합니다! DTO명만 보면 단일 데일리루틴을 전달한다고 착각할 수 있을 것 같아요.

2024-06-19 12:40 UTC, thguss commented on src/main/java/com/soptie/server/memberRoutine/controller/v2/dto/response/MemberDailyRoutineWithThemeListGetResponse.java
아래 추가 리뷰로 남겨놓겠습니다.

2024-06-19 12:41 UTC, thguss approved these changes
수고하셨습니다~ (정말루.. 😭😭)
DTO 이름 외 별 다른 이슈는 없어보여 우선 승인해두겠습니다.

2024-06-21 17:12 UTC, merged